### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by lihangshiwo** [benmoseley/FBPINNs#10]
I am a beginner and I would like to know if this method requires a dataset or data for training, which I didn't find in the case, thanks

**Comment by benmoseley** [comment]
@lihangshiwo thanks for the question. PINNs do not need labelled data for training, all you need to specify are 1) the initial/boundary conditions (when defining the boundary loss), 2) the PDE you want to solve (when defining the PDE loss) 3) collocation coordinates in the domain used for sampling the PINN loss over. If you want to solve an inverse problem with PINNs, then you can incorporate labelled training data (observations of the PDE solution) - example code for solving inverse problems is in the `fbpinns/examples` folder
