### ISSUE TITLE
Installation Issue of FBPINN

### ISSUE THREAD

**Issue by QifengHu** [benmoseley/FBPINNs#20]
Hi Dr. Moseley,

Thank you for sharing your code. I am trying to install the FBPINN package to explore its application in domain decomposition, but I'm encountering an issue with the instructions provided. When cloning the repository, I receive the following response:
![image](https://github.com/user-attachments/assets/ac6b54c1-f252-4058-a99e-a3ca64cd002a)
Could you please check if the repository path has changed or advise if there is something I might need to adjust on my end?

Thank you,
Qifeng

**Comment by a90091343** [comment]
`git clone https://github.com/benmoseley/FBPINNs.git` 试下呢

**Comment by QifengHu** [comment]
> `git clone https://github.com/benmoseley/FBPINNs.git` 试下呢

It worked. 谢谢!
