### ISSUE TITLE
Run Error, need help!

### ISSUE THREAD

**Issue by ruzhongliang** [benmoseley/FBPINNs#9]
I run the code "1. Defining your own problem - 1D harmonic oscillator", meet the error below:

[INFO] 2024-02-17 20:46:06 - <fbpinns.constants.Constants object at 0x0000025EF2406950>
run: test
domain: <class 'fbpinns.domains.RectangularDomainND'>
domain_init_kwargs: {'xmin': array([0.]), 'xmax': array([1.])}
problem: <class '__main__.HarmonicOscillator1D'>
problem_init_kwargs: {'d': 2, 'w0': 80}
decomposition: <class 'fbpinns.decompositions.RectangularDecompositionND'>
decomposition_init_kwargs: {'subdomain_xs': [array([0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429,
       0.35714286, 0.42857143, 0.5       , 0.57142857, 0.64285714,
       0.71428571, 0.78571429, 0.85714286, 0.92857143, 1.        ])], 'subdomain_ws': [array([0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15,
       0.15, 0.15, 0.15, 0.15])], 'unnorm': (0.0, 1.0)}
network: <class 'fbpinns.networks.FCN'>
network_init_kwargs: {'layer_sizes': [1, 32, 1]}
n_steps: 20000
scheduler: <class 'fbpinns.schedulers.AllActiveSchedulerND'>
scheduler_kwargs: {}
ns: ((200,),)
n_test: (500,)
sampler: grid
optimiser: <function adam at 0x0000025EF2756CB0>
optimiser_kwargs: {'learning_rate': 0.001}
seed: 0
summary_freq: 1000
test_freq: 1000
model_save_freq: 10000
show_figures: True
save_figures: False
clear_output: True
hostname: desktop-lostn3v

[INFO] 2024-02-17 20:46:07 - Total number of subdomains: 15
[INFO] 2024-02-17 20:46:08 - Total number of trainable parameters:
[INFO] 2024-02-17 20:46:08 - 	network: 1,455
[INFO] 2024-02-17 20:46:09 - Total number of constraints: 2
[INFO] 2024-02-17 20:46:09 - Computing exact solution..
[INFO] 2024-02-17 20:46:09 - Computing done
[INFO] 2024-02-17 20:46:09 - Getting test data inputs..
[INFO] 2024-02-17 20:46:12 - [i: 0/20000] Updating active inputs..
[INFO] 2024-02-17 20:46:12 - [i: 0/20000] Average number of points/dimension in active subdomains: 28.00
[INFO] 2024-02-17 20:46:15 - [i: 0/20000] Updating active inputs done (2.92 s)
[INFO] 2024-02-17 20:46:15 - [i: 0/20000] Compiling update step..
[INFO] 2024-02-17 20:46:15 - x_batch
[INFO] 2024-02-17 20:46:15 - (200, 1), float32, JVPTracer
[INFO] 2024-02-17 20:46:15 - x_take
[INFO] 2024-02-17 20:46:15 - (418, 1), float32, JVPTracer
[INFO] 2024-02-17 20:46:15 - x_batch
[INFO] 2024-02-17 20:46:15 - (1, 1), float32, JVPTracer
[INFO] 2024-02-17 20:46:15 - x_take
[INFO] 2024-02-17 20:46:15 - (2, 1), float32, JVPTracer
[INFO] 2024-02-17 20:46:17 - [i: 0/20000] Compiling done (2.35 s)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[7], line 4
      1 from fbpinns.trainers import FBPINNTrainer
      3 run = FBPINNTrainer(c)
----> 4 all_params = run.train()

File D:\py_test\PINN\FBPINNs-main\fbpinns\trainers.py:660, in FBPINNTrainer.train(self)
    657 # report initial model
    658 if i == 0:
    659     u_test_losses, start1, report_time = \
--> 660     self._report(i, pstep, fstep, u_test_losses, start0, start1, report_time,
    661                 u_exact, x_batch_test, test_inputs, all_params, all_opt_states, model_fns, problem, decomposition,
    662                 active, merge_active, active_opt_states, active_params, x_batch,
    663                 lossval)
    665 # take a training step
    666 lossval, active_opt_states, active_params = update(active_opt_states,
    667                              active_params, fixed_params, static_params_dynamic,
    668                              takess, constraints)# note compiled function only accepts dynamic arguments

File D:\py_test\PINN\FBPINNs-main\fbpinns\trainers.py:715, in FBPINNTrainer._report(self, i, pstep, fstep, u_test_losses, start0, start1, report_time, u_exact, x_batch_test, test_inputs, all_params, all_opt_states, model_fns, problem, decomposition, active, merge_active, active_opt_states, active_params, x_batch, lossval)
    713 # take test step
    714 if test_:
--> 715     u_test_losses = self._test(
    716         x_batch_test, u_exact, u_test_losses, x_batch, test_inputs, i, pstep, fstep, start0, active, all_params, model_fns, problem, decomposition)
    718 # save model
    719 if model_save_:

File D:\py_test\PINN\FBPINNs-main\fbpinns\trainers.py:736, in FBPINNTrainer._test(self, x_batch_test, u_exact, u_test_losses, x_batch, test_inputs, i, pstep, fstep, start0, active, all_params, model_fns, problem, decomposition)
    733 takes, all_ims, cut_all = test_inputs
    734 all_params_cut = {"static":cut_all(all_params["static"]),
    735                   "trainable":cut_all(all_params["trainable"])}
--> 736 u_test, wp_test_, us_test_, ws_test_, us_raw_test_ = FBPINN_model_jit(all_params_cut, x_batch_test, takes, model_fns, verbose=False)
    737 if all_params["static"]["problem"]["dims"][1] == 1:# 1D plots require full lines, not just hist stats
    739     m, ud, n = all_params["static"]["decomposition"]["m"], all_params["static"]["problem"]["dims"][0], x_batch_test.shape[0]

File D:\py_test\PINN\FBPINNs-main\fbpinns\trainers.py:320, in FBPINN_model_jit(all_params, x_batch, takes, model_fns, verbose)
    318 def FBPINN_model_jit(all_params, x_batch, takes, model_fns, verbose=True):
    319     all_params_dynamic, all_params_static = partition(all_params)
--> 320     return _FBPINN_model_jit(all_params_dynamic, all_params_static, x_batch, takes, model_fns, verbose)

    [... skipping hidden 12 frame]

File D:\py_test\PINN\FBPINNs-main\fbpinns\trainers.py:317, in _FBPINN_model_jit(all_params_dynamic, all_params_static, x_batch, takes, model_fns, verbose)
    314 @partial(jax.jit, static_argnums=(1,4,5))
    315 def _FBPINN_model_jit(all_params_dynamic, all_params_static, x_batch, takes, model_fns, verbose):
    316     all_params = combine(all_params_dynamic, all_params_static)
--> 317     return FBPINN_model(all_params, x_batch, takes, model_fns, verbose)

File D:\py_test\PINN\FBPINNs-main\fbpinns\trainers.py:164, in FBPINN_model(all_params, x_batch, takes, model_fns, verbose)
    162 # apply POU and sum
    163 u = jnp.concatenate([us, ws], axis=1)# (s, ud+1)
--> 164 u = jax.ops.segment_sum(u, p_take, indices_are_sorted=False, num_segments=len(np_take))# (_, ud+1)
    165 wp = u[:,-1:]
    166 u = u[:,:-1]/wp

File D:\ProgramData\anaconda3\envs\py310nn\lib\site-packages\jax\_src\ops\scatter.py:251, in segment_sum(data, segment_ids, num_segments, indices_are_sorted, unique_indices, bucket_size, mode)
    201 def segment_sum(data: ArrayLike,
    202                 segment_ids: ArrayLike,
    203                 num_segments: int | None = None,
   (...)
    206                 bucket_size: int | None = None,
    207                 mode: lax.GatherScatterMode | None = None) -> Array:
    208   """Computes the sum within segments of an array.
    209 
    210   Similar to TensorFlow's `segment_sum
   (...)
    249     Array([1, 5, 4], dtype=int32)
    250   """
--> 251   return _segment_update(
    252       "segment_sum", data, segment_ids, lax.scatter_add, num_segments,
    253       indices_are_sorted, unique_indices, bucket_size, reductions.sum, mode=mode)

File D:\ProgramData\anaconda3\envs\py310nn\lib\site-packages\jax\_src\ops\scatter.py:183, in _segment_update(name, data, segment_ids, scatter_op, num_segments, indices_are_sorted, unique_indices, bucket_size, reducer, mode)
    180 if bucket_size is None:
    181   out = jnp.full((num_segments,) + data.shape[1:],
    182                  _get_identity(scatter_op, dtype), dtype=dtype)
--> 183   return _scatter_update(
    184     out, segment_ids, data, scatter_op, indices_are_sorted,
    185     unique_indices, normalize_indices=False, mode=mode)
    187 # Bucketize indices and perform segment_update on each bucket to improve
    188 # numerical stability for operations like product and sum.
    189 assert reducer is not None

File D:\ProgramData\anaconda3\envs\py310nn\lib\site-packages\jax\_src\ops\scatter.py:80, in _scatter_update(x, idx, y, scatter_op, indices_are_sorted, unique_indices, mode, normalize_indices)
     77 # XLA gathers and scatters are very similar in structure; the scatter logic
     78 # is more or less a transpose of the gather equivalent.
     79 treedef, static_idx, dynamic_idx = jnp._split_index_for_jit(idx, x.shape)
---> 80 return _scatter_impl(x, y, scatter_op, treedef, static_idx, dynamic_idx,
     81                      indices_are_sorted, unique_indices, mode,
     82                      normalize_indices)

File D:\ProgramData\anaconda3\envs\py310nn\lib\site-packages\jax\_src\ops\scatter.py:115, in _scatter_impl(x, y, scatter_op, treedef, static_idx, dynamic_idx, indices_are_sorted, unique_indices, mode, normalize_indices)
    112 x, y = promote_dtypes(x, y)
    114 # Broadcast `y` to the slice output shape.
--> 115 y = jnp.broadcast_to(y, tuple(indexer.slice_shape))
    116 # Collapse any `None`/`jnp.newaxis` dimensions.
    117 y = jnp.squeeze(y, axis=indexer.newaxis_dims)

File D:\ProgramData\anaconda3\envs\py310nn\lib\site-packages\jax\_src\numpy\lax_numpy.py:1218, in broadcast_to(array, shape)
   1214 @util.implements(np.broadcast_to, lax_description="""\
   1215 The JAX version does not necessarily return a view of the input.
   1216 """)
   1217 def broadcast_to(array: ArrayLike, shape: DimSize | Shape) -> Array:
-> 1218   return util._broadcast_to(array, shape)

File D:\ProgramData\anaconda3\envs\py310nn\lib\site-packages\jax\_src\numpy\util.py:428, in _broadcast_to(arr, shape)
    426 if nlead < 0 or not compatible:
    427   msg = "Incompatible shapes for broadcasting: {} and requested shape {}"
--> 428   raise ValueError(msg.format(arr_shape, shape))
    429 diff, = np.where(tuple(not core.definitely_equal(arr_d, shape_d)
    430                        for arr_d, shape_d in safe_zip(arr_shape, shape_tail)))
    431 new_dims = tuple(range(nlead)) + tuple(nlead + diff)

ValueError: Incompatible shapes for broadcasting: (1046, 2) and requested shape (1046, 1, 2)

**Comment by tirtho109** [comment]
I faced the same issue. I fixed it by installing `pip install -U "jax[cpu]"` [link](https://github.com/google/jax#installation), and rest of the dependencies 
`"optax>=0.1.4", "numpy>=1.24.2", "scipy>=1.10.1", "matplotlib>=3.7.1", "tensorboardX>=2.6", "ipython>=8.12.0"]`

**Comment by avd28** [comment]
> I faced the same issue. I fixed it by installing `pip install -U "jax[cpu]"` [link](https://github.com/google/jax#installation), and rest of the dependencies `"optax>=0.1.4", "numpy>=1.24.2", "scipy>=1.10.1", "matplotlib>=3.7.1", "tensorboardX>=2.6", "ipython>=8.12.0"]`

Hi Tirtho, could you add some more detail on how this fixed the issue for you? Did you uninstall the default jaxlib and then install jax[cpu] ?

**Comment by jseeyave** [comment]
I have the same issue. It also occurs when I run main.py in the multi-level paper. 
Please advise

**Comment by tirtho109** [comment]
> > I faced the same issue. I fixed it by installing `pip install -U "jax[cpu]"` [link](https://github.com/google/jax#installation), and rest of the dependencies `"optax>=0.1.4", "numpy>=1.24.2", "scipy>=1.10.1", "matplotlib>=3.7.1", "tensorboardX>=2.6", "ipython>=8.12.0"]`
> 
> Hi Tirtho, could you add some more detail on how this fixed the issue for you? Did you uninstall the default jaxlib and then install jax[cpu] ?

Hi, Yes, I have uninstalled everything and created a new python environment as suggested. Afterward I installed the `jax[cpu]` version and so on.

**Comment by benmoseley** [comment]
This looks like an issue with `jax.ops.segment_sum` and the internal jax operations not broadcasting correctly @jseeyave @avd28 @ruzhongliang @tirtho109 can you provide more details about your OS / python version / jax version / whether you are running on GPU or CPU? If we can produce a minimal version of this bug (a script which simply calls `jax.ops.segment_sum` with the same shape arrays which cause the error above) we can raise an issue in the main JAX repo

**Comment by jseeyave** [comment]
I'm running on CPU, OS is Ubuntu 20.04.5 LTS, Python 3.9.5, jax/jaxlib-0.4.25.
Please see screenshot below when I try to run '1. Defining your own problem - 1D harmonic oscillator'
'jax.ops.segment_sum' is called twice in trainers.py. I added 2 print statement after each call. They are in the screenshot between the [info] lines. e.g. "line 164. trainers.py. np.size(u)= 400"
![Screenshot from 2024-03-15 11-27-41](https://github.com/benmoseley/FBPINNs/assets/163351029/e961b0d9-db6f-4776-b496-4fa5ebd7e950)
Please let me know if there is anything else I can provide to help debug the issue.

**Comment by benmoseley** [comment]
I narrowed it down and found that there is inconsistency between the shapes of the output arrays of `jnp.unique` between different jax versions, see this bug report: https://github.com/google/jax/issues/20274
For now to fix the error, please downgrade jax to an earlier version (I am not sure exactly which version this bug appears, but 0.4.19 definitely works).

**Comment by benmoseley** [comment]
Ok I have patched, closing this issue as it should be fixed now.
